### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/.apmrc'

### ISSUE THREAD

**Issue by jusher** [smonami/hacker-news-side-panel#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [hacker-news-side-panel](https://github.com/smonami/hacker-news-side-panel) package, v1.0.0
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/jennifersusher/.atom/.apmrc'

```
At fs.js:584

Error: ENOENT: no such file or directory, open '/Users/jennifersusher/.atom/.apmrc'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:427:29)
    at PropertiesReader.append (/Users/jennifersusher/.atom/packages/hacker-news-side-panel/node_modules/properties-reader/src/PropertiesReader.js:49:26)
    at new PropertiesReader (/Users/jennifersusher/.atom/packages/hacker-news-side-panel/node_modules/properties-reader/src/PropertiesReader.js:16:14)
    at PropertiesReader.builder (/Users/jennifersusher/.atom/packages/hacker-news-side-panel/node_modules/properties-reader/src/PropertiesReader.js:276:16)
    at new NetworkService (/Users/jennifersusher/.atom/packages/hacker-news-side-panel/lib/network-service.js:21:20)
    at Object.updateView (/Users/jennifersusher/.atom/packages/hacker-news-side-panel/lib/hacker-news-side-panel.js:43:26)
    at Object.toggle (/Users/jennifersusher/.atom/packages/hacker-news-side-panel/lib/hacker-news-side-panel.js:55:67)
    at atom-workspace.hackerNewsSidePanelToggle (/Users/jennifersusher/.atom/packages/hacker-news-side-panel/lib/hacker-news-side-panel.js:26:51)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/jennifersusher/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Users/jennifersusher/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/jennifersusher/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Users/jennifersusher/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Users/jennifersusher/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
     -0:01.5.0 hacker-news-side-panel:toggle (atom-text-editor.editor.emacs-plus.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-swift, v1.0.2
build-xcodebuild, v0.2.0
emacs-plus, v0.11.0
hacker-news, v0.2.2
hacker-news-side-panel, v1.0.0
language-swift, v0.4.0
linter, v1.11.4
linter-sourcekitten-syntax, v0.1.1
linter-swift-package-manager, v0.1.0
linter-swiftc, v2.0.0
linter-swiftlint, v1.1.0
minimap, v4.24.1

# Dev
No dev packages
```

**Comment by smonami** [comment]
Thanks for reporting the issue. Fixed!
